### ISSUE TITLE
[Bug] TypeError: Cannot read property '_isDestroyed' of undefined on mount the component

### ISSUE THREAD

**Issue by kauanschaeffer** [storybookjs/testing-vue#5]
### Describe the bug

Im having this error when mounting a component. I'm not sure why this is happening and couldnt reproduce with testing-vue linked since the error stops when I link it.
The thing is, this error doesnt happen when commonly rendering the component, so I think it might be something related to the construction of it.

### Steps to reproduce the behavior

I just rendered my component from the story and the error showed.

### Expected behavior

This error shouldnt happen.

### Screenshots and/or logs

```javascript
  TypeError: Cannot read property '_isDestroyed' of undefined
      at destroy (node_modules/vue/dist/vue.common.dev.js:3160:28)
      at invokeDestroyHook (node_modules/vue/dist/vue.common.dev.js:6105:59)
      at invokeDestroyHook (node_modules/vue/dist/vue.common.dev.js:6110:9)
      at invokeDestroyHook (node_modules/vue/dist/vue.common.dev.js:6110:9)
      at invokeDestroyHook (node_modules/vue/dist/vue.common.dev.js:6110:9)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.common.dev.js:6456:30)
      at VueComponent.Vue.$destroy (node_modules/vue/dist/vue.common.dev.js:3998:8)
      at destroy (node_modules/vue/dist/vue.common.dev.js:3162:27)
      at invokeDestroyHook (node_modules/vue/dist/vue.common.dev.js:6105:59)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.common.dev.js:6456:30)
      at VueComponent.Vue.$destroy (node_modules/vue/dist/vue.common.dev.js:3998:8)
      at destroy (node_modules/vue/dist/vue.common.dev.js:3162:27)
      at invokeDestroyHook (node_modules/vue/dist/vue.common.dev.js:6105:59)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.common.dev.js:6456:30)
      at VueComponent.Vue.$destroy (node_modules/vue/dist/vue.common.dev.js:3998:8)
      at destroy (node_modules/vue/dist/vue.common.dev.js:3162:27)
      at invokeDestroyHook (node_modules/vue/dist/vue.common.dev.js:6105:59)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.common.dev.js:6456:30)
      at VueComponent.Vue.$destroy (node_modules/vue/dist/vue.common.dev.js:3998:8)
      at VueWrapper.destroy (node_modules/@testing-library/vue/node_modules/@vue/test-utils/dist/vue-test-utils.js:10550:13)
      at cleanupAtWrapper (node_modules/@testing-library/vue/dist/render.js:124:13)
          at Set.forEach (<anonymous>)
      at cleanup (node_modules/@testing-library/vue/dist/render.js:115:19)
      at Object.<anonymous> (node_modules/@testing-library/vue/dist/index.js:54:25)
```

### Environment

 - OS: Linux Mint 20
 - Node.js version: 12.9.0
 - Yarn version: 1.22.15

### Additional context

I also created an issue on testing-library/vue regarding the unhandled exception, but I do think that the root cause is here. I'm opening  this issue so we can talk and maybe check if anyone else had this problem.

**Comment by yannbf** [comment]
Hey @kauanschaeffer thanks for opening this issue! How does your story look like? Can you give some additional context to this?

@elevatebart do you happen to have any idea what's going on? Thanks!

**Comment by kauanschaeffer** [comment]
It's a pretty straightforward story, it's available here: https://github.com/comexio/design-system/blob/homol/docs/stories/components/inputs/LInputTag.stories.js
